### ISSUE TITLE
请问插件支持移动端吗？

### ISSUE THREAD

**Issue by PhoenixPtt** [sunxvming/obsidian-vscode-editor#1]
我在andriod系统上无法开启插件，如果确实如此，希望增加移动端的支持

**Comment by sunxvming** [comment]
andriod系统上我没测试，但是在浏览器中模拟手机测试是的，你把插件里面的manifest.json中的isDesktopOnly改成false试试，应该就可以用了

**Comment by PhoenixPtt** [comment]
刚测试了，在移动端可以启用，谢谢
