### ISSUE TITLE
BUG: Fails to install from community plugins in Obsidian

### ISSUE THREAD

**Issue by DrSapling** [sunxvming/obsidian-vscode-editor#10]
**Your environment**
SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.16
	Operating system: Windows 10 Home 10.0.22621
		(It is Windows 11 Home)
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Dark Moss v1.0.0
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 4
	Plugins enabled: 0

**Describe the bug**
The lpugin "Fails to install" right after pressing the install button.

**To Reproduce**
1. Go to 'Community plugins'
2. Click on 'Install'
3. See error

**Screenshots**
![image](https://github.com/sunxvming/obsidian-vscode-editor/assets/84985477/404a9a24-7f69-4b29-91b0-092c55dd59f9)

**Comment by sunxvming** [comment]
sorry, I got the plugin version wrong，so it can't install. It has been fixed.
