### ISSUE TITLE
BUG: *.h和*.hpp文件不会显示

### ISSUE THREAD

**Issue by pigparadise** [sunxvming/obsidian-vscode-editor#18]
c和cpp文件是能正常显示的，但看不到头文件

**Comment by sunxvming** [comment]
你需要在插件的设置界面设置一下要显示的文件后缀，
![image](https://github.com/sunxvming/obsidian-vscode-editor/assets/16833443/ee85dcdc-3ada-4a29-a31f-4c53f32737fc)
