### ISSUE TITLE
FR: Add PowerShell Support

### ISSUE THREAD

**Issue by jimbrig** [sunxvming/obsidian-vscode-editor#19]
Would be nice to be able to edit PowerShell code files from within Obsidian: 

Primarily would just want support for default `.ps1` script files. 

But there are some other PowerShell related extensions that are relevant:

- `.ps1`: Default Script File
- `.psm1`: Module (Script) File
- `.psd1`: PowerShell Data File | Module Manifest
- `.ps1xml`: Format and Type Definition Files
- `.pssc`: Session Configuration File
- `.psrc`: Session Role Capability File

Related additional support for `C#`, `F#`, `VBS`, etc. would be awesome too!

**Comment by SomeZyla** [comment]
This would be really nice!  

You can add the extensions into the plugin options so that at least the files will not try to open with an external app, however, there is no syntax coloring.

- `.sh` would be nice too for shell scripting
