### ISSUE TITLE
BUG: not working

### ISSUE THREAD

**Issue by DZL1943** [sunxvming/obsidian-vscode-editor#2]
**Your environment**
Please run `Command Palette/Show Debug info` in Obsidian and paste the result here.

SYSTEM INFO:
	Obsidian version: v1.4.14
	Installer version: v1.4.13
	Operating system: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:34 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8103 23.0.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v7.3.2
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 113
	Plugins enabled: 63
		1: Buttons v0.4.19
		2: Canvas Mindmap v0.1.3
		3: Commander v0.5.0
		4: Cycle In Sidebar v1.0.2
		5: Dataview v0.5.59
		6: Editing Toolbar v2.3.1
		7: File Tree Alternative Plugin v2.3.6
		8: Floating Search v3.4.5
		9: floating toc v2.3.0
		10: Homepage v3.5.2
		11: Link Exploder v0.3.0
		12: Markdown Table Editor v0.3.1
		13: Multi-Column Markdown v0.8.3
		14: MySnippets v1.2.3
		15: Natural Language Dates v0.6.1
		16: Advanced URI v1.38.1
		17: Excalidraw v1.9.23
		18: Excel to Markdown Table v0.4.0
		19: Export Image plugin v1.0.3
		20: Heading Shifter v1.5.1
		21: Hider v1.3.1
		22: Kanban v1.5.3
		23: Linter v1.20.0
		24: Minimal Theme Settings v7.3.0
		25: Outliner v4.8.0
		26: Style Settings v1.0.7
		27: Tasks v4.9.0
		28: Clear Unused Images v1.1.0
		29: Quick Explorer v0.2.8
		30: Settings Search v1.3.10
		31: Advanced Tables v0.19.1
		32: Tag Wrangler v0.6.1
		33: Templater v1.16.3
		34: Paste URL into selection v1.7.0
		35: Any Block v2.2.0
		36: QuickAdd v1.4.0
		37: Surfing v0.8.16
		38: Regex Find/Replace v1.2.0
		39: Shell commands v0.20.0
		40: Custom File Explorer sorting v1.9.2
		41: Calendar v1.5.10
		42: Control Characters v0.3.0
		43: Keyboard Analyzer v0.1.3
		44: Chronology v1.1.9
		45: Trash Explorer v1.2.2
		46: Sidebar Expand on Hover v1.0.1
		47: Cursor Location v0.3.1
		48: Quick Switcher++ v3.3.7
		49: Open In New Tab v1.0.9
		50: Hover Editor v0.11.14
		51: Zoom v1.1.2
		52: Hotkeys++ v0.2.7
		53: Daily Notes Editor v0.1.4
		54: MAKE.md v0.7.31
		55: Sort & Permute lines v0.7.0
		56: Quick Plugin Switcher v3.0.1
		57: Attachment Management v0.8.4
		58: Projects v1.16.5
		59: Easy Typing v5.1.10
		60: Fuzzy Chinese Pinyin v2.7.3
		61: Various Complements v9.0.0
		62: Codeblock Customizer v1.2.5
		63: VSCode Editor v1.0.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Describe the bug**

安装后显示需要更新, 启用后没有设置项, 也没有命令, 打开 js 文件仍然会跳转到本机 vscode 应用打开.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sunxvming** [comment]
俺猜测可能是因为和别的插件有冲突了，然后报错不能正常运行，你可以在obsidian中 按Ctril + Shift + i 快捷键跳出调试面板，看看有没有报错
![image](https://github.com/sunxvming/obsidian-vscode-editor/assets/16833443/2e4f1e99-d94b-4c2e-a2d8-345b30877350)

**Comment by sunxvming** [comment]
出现这个错误是因为可能是和obsidian的另一个插件Code Files冲突了，Code Files这个插件也是提供对代码文件的编辑功能，但它们只能同时存在一个，因此你需要把Code Files这个插件关闭掉才能使用VSCode Editor plugin
