### ISSUE TITLE
BUG: The VSCode plugin is not seen in Community Plugin Section 

### ISSUE THREAD

**Issue by erdemalpkaya** [sunxvming/obsidian-vscode-editor#3]
I uninstalled and re-installed multiple times but still I cannot see the plugin in the community plugin section. Please check the attachment

![CleanShot 2023-10-13 at 10 17 29](https://github.com/sunxvming/obsidian-vscode-editor/assets/24259112/0f9ce189-6d01-4651-8b0a-3ef4439aff1b)

**Comment by sunxvming** [comment]
I guess it may be because there is a conflict with other plug-ins, and then the error can not run normally. You can press Ctril + Shift + i shortcut keys in obsidian to jump out of the debugging panel and check whether there is an error. If there is one, please send it to me, thank you
![image](https://github.com/sunxvming/obsidian-vscode-editor/assets/16833443/2e4f1e99-d94b-4c2e-a2d8-345b30877350)

**Comment by sunxvming** [comment]
> I uninstalled and re-installed multiple times but still I cannot see the plugin in the community plugin section. Please check the attachment
> 
> ![CleanShot 2023-10-13 at 10 17 29](https://user-images.githubusercontent.com/24259112/274841149-0f9ce189-6d01-4651-8b0a-3ef4439aff1b.png)

Do you have any discard account or other chat software tools? We can solve it on the chat tool, which will be faster

**Comment by erdemalpkaya** [comment]
Here is the Issue result. There were many issues bit only the one related with VS Code Editor

![CleanShot 2023-10-15 at 14 37 45](https://github.com/sunxvming/obsidian-vscode-editor/assets/24259112/75e27f20-b6af-4ee8-82c8-af5937063f4a)

**Comment by erdemalpkaya** [comment]
.analyst my discord name

**Comment by sunxvming** [comment]
This error occurs because it conflicts with another plug-in of obsidian, Code Files, which also provides the editing function of Code Files, but they can only exist at the same time. Therefore, you need to close the Code Files plugin to use the VSCode Editor plugin

**Comment by sjhsbhqf** [comment]
I have this problem because I have installed this plug-in HTML Reader before
