### ISSUE TITLE
Suggestion: Clearly point out how it compares to the other solution

### ISSUE THREAD

**Issue by MarioRicalde** [sunxvming/obsidian-vscode-editor#5]
There is another Monaco-in-Obsidian plugin available. The main issue with that one is that it depends on a third party web service.

It might be helpful for the plugin to note if this one is different from that one.

**Comment by sunxvming** [comment]
Thanks for your suggestion！I will update the plugin description.

**Comment by MarioRicalde** [comment]
Great job. One thing that was not left clear is if this plugin has managed to include the editor within instead of linking a third party API
