### ISSUE TITLE
BUG: conflict with surfing plugin

### ISSUE THREAD

**Issue by ksdavidc** [sunxvming/obsidian-vscode-editor#6]
This is a follow up to 
https://github.com/sunxvming/obsidian-vscode-editor/issues/3#issue-1941479799 

I found a similar conflict with the sufring plugin and was able to solve it by:

1. disabling surfing, enable vscode
2. removing html from vscode settings
3. reenable surfing (will give error. Ignore the error)
4. reload the vault.

**Comment by lordkekz** [comment]
Had the same issue, thanks for the workaround!
