### ISSUE TITLE
FR: word wrap

### ISSUE THREAD

**Issue by ksdavidc** [sunxvming/obsidian-vscode-editor#7]
word wrap pretty much says it all.

**Comment by sunxvming** [comment]
Your suggestion is very good, I will add this setting as soon as possible

**Comment by sunxvming** [comment]
Already supports automatic code wrapping, and toggles it with `alt + z`. Now you can go to update the plugin.

**Comment by ksdavidc** [comment]
hmm. At least for me this does not work on my mac. I am using an International keyboard and get this Ω characters if I try alt (aka option). Could the alt-z be configurable?
